CUSTOM_DATE_YEAR := $(shell date +%Y)
CUSTOM_DATE_MONTH := $(shell date +%m)
CUSTOM_DATE_DAY := $(shell date +%d)
CUSTOM_DATE_HOUR := $(shell date +%H)
CUSTOM_DATE_MINUTE := $(shell date +%M)
CUSTOM_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) CST' +%s)
CUSTOM_BUILD_DATE := $(shell date +%Y%m%d)

CUSTOM_PLATFORM_VERSION := 14.0
PIXELEX_VERSION := Aaron
CUSTOM_BUILDTYPE ?= SNAPSHOT

CUSTOM_VERSION := PixelOS-Plus_$(CUSTOM_BUILD)-$(PIXELEX_VERSION)-$(CUSTOM_BUILDTYPE)-$(CUSTOM_BUILD_DATE)
CUSTOM_VERSION_PROP := fourteen

ifeq ($(CUSTOM_RELEASE),true)
    CUSTOM_BUILDTYPE := RELEASE
endif

PRODUCT_SYSTEM_PROPERTIES += \
  ro.custom.build.version=$(PIXELEX_VERSION) \
  ro.custom.maintainer=$(CUSTOM_MAINTAINER)
